library(LaplacesDemon)
library(distcrete)
library(dplyr)
library(tibble)
library(mixtree)
library(purrr)

# =================================================
# Forest Simulation
# =================================================

#' Simulate an Epidemic Forest
#'
#' Generates multiple plausible transmission trees given \code{tree} and \code{params}.
#'
#' @param tree A tibble representing the reference tree (from \code{build_tree()}).
#' @param params List of epidemic parameters generated by \code{build_params()}.
#' @param forest_size Integer. The total number of transmission trees to generate. Default is 200.
#'
#' @return A matrix of ancestries. Where each row corresponds to a tree and each column to a case (excluding the root).
#' For example, entry [i, j] indicates the infector of case j in tree i.
build_forest <- function(tree, params, forest_size = 200L) {
  simulate_tree <- function() {
    n_cases <- length(tree$to)

    # Sample offspring for all cases
    R <- params$offspring_dist$r(n_cases)

    # Ensure first case has R >= 1
    if (R[1] < 1) {
      R[1] <- LaplacesDemon::rtrunc(
        n = 1,
        spec = params$offspring_dist$name,
        a = 0,
        size = params$offspring_dist$parameters$k,
        mu = params$offspring_dist$parameters$R
      )
    }
    # Initialise tree
    sim_tree <- tibble(
      j = NA_character_, # infector
      i = tree$to, # infectee
      date = tree$date, # infectee's date is fixed from reference tree
      R = R # sampled offspring
    )

    generation_time_pmf <- params$generation_time$d(0:params$duration)

    for (row in 2:nrow(sim_tree)) {
      t_i <- sim_tree$date[row]

      j_candidates <- sim_tree |>
        filter(date < t_i) |>
        mutate(foi = R * generation_time_pmf[t_i - date + 1])

      j_chosen <- sample(
        j_candidates$i,
        1,
        prob = j_candidates$foi / sum(j_candidates$foi)
      )
      sim_tree$j[row] <- j_chosen
    }

    stopifnot(sum(is.na(sim_tree$j)) == 1) # one intro only

    sim_tree <- sim_tree |>
      slice(-1) |>
      rename(from = j, to = i)

    mixtree::validate_tree(sim_tree)

    # Return vector of ancestries to save space (i is always 1:n)
    ancestries <- as.vector(sim_tree$from)
    return(ancestries)
  }
  # Rows = forest ID, Columns = case ID
  forest <- t(replicate(forest_size, simulate_tree(), simplify = TRUE))
  colnames(forest) <- tree$to[-1] # Exclude root case
  if (nrow(forest) != forest_size) {
    stop("Forest size mismatch: expected ", forest_size, ", got ", nrow(forest))
  }
  return(forest)
}

build_forest_safe <- function(
  tree,
  params,
  forest_size = 200L,
  max_attempts = 10L
) {
  attempt <- 1L
  repeat {
    result <- tryCatch(
      build_forest(tree, params, forest_size),
      error = function(e) e
    )

    if (!inherits(result, "error")) {
      return(result)
    }

    if (attempt >= max_attempts) {
      stop(
        "Failed to build forest after ",
        max_attempts,
        " attempts. ",
        "Error: ",
        conditionMessage(result)
      )
    }

    message(
      "Retrying forest build (attempt ",
      attempt + 1,
      "/",
      max_attempts,
      ")..."
    )
    attempt <- attempt + 1L
  }
}


# =================================================
# Load Data
# =================================================
forest_grid <- readRDS("data/tree_grid.rds") |>
  mutate(
    epidemic_size = map_dbl(tree, nrow)
  ) |>
  inner_join(
    readRDS("data/param_grid.rds") |> select(param_id, params, epidemic_size),
    by = "epidemic_size",
    relationship = "many-to-many"
  )

# =================================================
# hipercow job function
# =================================================
forest_job <- function(idx, output_dir = "data/forest_grid") {
  dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

  f <- forest_grid[idx, ] |>
    mutate(
      forest = purrr::map2(tree, params, build_forest_safe),
      forest_id = paste0(tree_id, "_", param_id)
    ) |>
    select(forest_id, forest)

  purrr::pwalk(f, function(forest_id, forest) {
    file_path <- file.path(output_dir, paste0("forest_", forest_id, ".rds"))
    saveRDS(forest, file_path, compress = "xz")
  })

  return(invisible(f))
}
