#' Simulate an Epidemic Forest (offspring-first allocation)
#'
#' Generates multiple plausible transmission trees given \code{tree} and
#' \code{params}.  Unlike the original \code{build_forest()}, this version
#' samples offspring counts *first* from the NegBin(R, k) distribution and
#' then assigns children to parents, guaranteeing that the marginal offspring
#' distribution of each forest tree matches the assumed NegBin — up to the
#' sum constraint Σ O_j = n − 1.
#'
#' @param tree A tibble representing the reference tree (from \code{build_tree()}).
#' @param params List of epidemic parameters generated by \code{build_params()}).
#' @param forest_size Integer. The total number of transmission trees to
#'   generate. Default is 200.
#' @param max_attempts Integer. Maximum redistribution attempts before falling
#'   back to a fresh sample. Default is 500.
#'
#' @return A matrix of ancestries (rows = trees, columns = cases excl. root).
build_forest <- function(tree, params, forest_size = 200L, max_attempts = 500L) {

  simulate_tree <- function() {
    n_cases  <- length(tree$to)
    target   <- n_cases - 1L          # total edges in a tree

    generation_time_pmf <- params$generation_time$d(0:params$duration)

    # ------------------------------------------------------------------
    # Step 1: Sample offspring counts & condition on sum = target
    # ------------------------------------------------------------------
    #  Strategy: sample from NegBin, then nudge the vector so that
    #  Σ O_j = n − 1 while staying as close to the original draw as
    #  possible.  Root is guaranteed O >= 1.
    O <- params$offspring_dist$r(n_cases)

    # Root must have ≥ 1 offspring
    if (O[1] < 1L) {
      O[1] <- LaplacesDemon::rtrunc(
        n    = 1,
        spec = params$offspring_dist$name,
        a    = 0,
        size = params$offspring_dist$parameters$k,
        mu   = params$offspring_dist$parameters$R
      )
    }

    # Redistribute to hit the target sum
    surplus <- sum(O) - target

    attempt <- 0L
    while (surplus != 0L && attempt < max_attempts) {
      attempt <- attempt + 1L
      if (surplus > 0L) {
        # Remove one offspring from a random case with O > 0 (keep root ≥ 1)
        eligible <- which(O > 0L & (seq_along(O) != 1L | O > 1L))
        idx <- sample(eligible, 1L)
        O[idx] <- O[idx] - 1L
        surplus <- surplus - 1L
      } else {
        # Add one offspring to a random case
        idx <- sample.int(n_cases, 1L)
        O[idx] <- O[idx] + 1L
        surplus <- surplus + 1L
      }
    }

    # Safety net: if redistribution stalled, resample the whole vector
    if (surplus != 0L) {
      O <- as.integer(rmultinom(1, target, rep(1, n_cases)))
      O[1] <- max(O[1], 1L)
      # Re-adjust if root bump broke the sum
      if (sum(O) > target) {
        extras <- which(O > 0L & seq_along(O) != 1L)
        O[extras[1]] <- O[extras[1]] - 1L
      }
    }

    stopifnot(sum(O) == target)

    # ------------------------------------------------------------------
    # Step 2: Assign children to parents respecting offspring counts
    # ------------------------------------------------------------------
    #  For each child (chronologically), choose a parent that still has
    #  remaining capacity, weighted by generation-time probability.
    remaining <- O                       # remaining capacity per case
    sim_tree <- tibble(
      j    = NA_character_,
      i    = tree$to,
      date = tree$date
    )

    for (row in 2:nrow(sim_tree)) {
      t_i <- sim_tree$date[row]

      j_candidates <- sim_tree |>
        slice(which(sim_tree$date < t_i)) |>
        mutate(
          idx       = which(sim_tree$date < t_i),
          remaining = remaining[idx],
          gt_weight = generation_time_pmf[t_i - date + 1]
        ) |>
        filter(remaining > 0L)

      if (nrow(j_candidates) == 0L) {
        # Fallback: if no parent has capacity, allow any earlier case
        j_candidates <- sim_tree |>
          slice(which(sim_tree$date < t_i)) |>
          mutate(
            idx       = which(sim_tree$date < t_i),
            remaining = 1L,
            gt_weight = generation_time_pmf[t_i - date + 1]
          )
      }

      probs <- j_candidates$remaining * j_candidates$gt_weight
      if (sum(probs) == 0) probs <- rep(1, nrow(j_candidates))
      probs <- probs / sum(probs)

      chosen_row <- sample(seq_len(nrow(j_candidates)), 1L, prob = probs)
      chosen_idx <- j_candidates$idx[chosen_row]

      sim_tree$j[row]      <- j_candidates$i[chosen_row]
      remaining[chosen_idx] <- remaining[chosen_idx] - 1L
    }

    stopifnot(sum(is.na(sim_tree$j)) == 1L)

    sim_tree <- sim_tree |>
      slice(-1) |>
      rename(from = j, to = i)

    mixtree::validate_tree(sim_tree)

    as.vector(sim_tree$from)
  }

  forest <- t(replicate(forest_size, simulate_tree(), simplify = TRUE))
  colnames(forest) <- tree$to[-1]

  if (nrow(forest) != forest_size) {
    stop("Forest size mismatch: expected ", forest_size, ", got ", nrow(forest))
  }

  return(forest)
}
