# =================================================
# Miscellaneous functions
# =================================================
#' Relabel IDs by Onset Date
#'
#' Assigns new integer labels to a vector of IDs, ordered by their associated onset dates.
#' Returns a named vector mapping the original IDs to their new labels.
#'
#' @param id Character or factor vector of unique IDs.
#' @param date Vector of onset dates corresponding to \code{id}. Must be the same length as \code{id}.
#'
#' @return Character vector of new labels, named by original IDs and ordered as \code{id}.

label_ids <- function(id, date) {
  ordered_ids <- id[order(date)]
  new_labels <- as.character(seq_along(ordered_ids))
  setNames(new_labels, ordered_ids)[id]
}

#' Relabel Data Frame ID Columns
#' Replaces values in specified ID columns of a data frame with new labels ordered by onset date.
#' All ID columns are relabelled consistently using the same mapping.
#'
#' @param df Data frame. The transmission tree
#' @param id_cols Character vector of column names in \code{df} to relabel (e.g., \code{c("from", "to")}).
#' @param date_col Character. Name of the column containing onset or infection dates. Default in "date"
#'
#' @return Data frame with updated ID columns.
relabel_tree <- function(df, id_cols, date_col = "date") {
  ids <- label_ids(df[[id_cols[2]]], df[[date_col]]) # Use the 2nd column for labelling

  # Apply the relabelling all specified id columns
  for (col in id_cols) {
    df[[col]] <- ids[df[[col]]]
  }

  return(df)
}

# =================================================
# Tree generation
# =================================================

# -------------------------------------------------
# Epidemic Parameters
# -------------------------------------------------
# Relevant functions to produce the true transmission tree.

print.params <- function(x, ...) {
  cat("-------------------\n")
  cat("Epidemic Parameters\n")
  cat("-------------------\n")

  # Offspring distribution
  cat("Distributions:\n")
  cat(" Offspring:\n")
  cat("  name:", x$offspring_dist$name, "\n")
  cat("  parameters:\n")
  cat("   k (size):", x$offspring_dist$parameters$k, "\n")
  cat("   R (mu):", x$offspring_dist$parameters$R, "\n\n")

  # Generation time distribution
  cat(" Generation time:\n")
  cat("  name:", x$generation_time$name, "\n")
  cat("  parameters:\n")
  cat("   shape:", x$generation_time$parameters$shape, "\n")
  cat("   scale:", x$generation_time$parameters$scale, "\n")
  cat("   mu:", x$generation_time$parameters$mu, "\n")
  cat("   sd:", x$generation_time$parameters$sd, "\n")
  cat("   cv:", x$generation_time$parameters$cv, "\n\n")

  # Other parameters
  cat("Simulation settings:\n")
  cat(" epidemic size:", x$epidemic_size, "\n")
  cat(" simulation duration:", x$duration, "\n")
  cat(" replicates:", x$replicates, "\n")

  invisible(x)
}

#' Build Epidemic Parameters
#'
#' Constructs a list of parameters for simulating the true transmission tree.
#'
#' @param off_R Numeric. Mean of the negative binomial offspring distribution.
#' @param off_k Numeric. Dispersion parameter of the negative binomial offspring distribution.
#' @param gt_mu Numeric. Mean generation time (gamma distribution).
#' @param gt_sd Numeric. Standard deviation of generation time (gamma distribution).
#' @param epidemic_size Integer. The epidemic's final size (number of cases).
#' @param duration Integer. Duration of the simulation (in days).
#' @param replicates Integer. Nnumber of trees to simulate.
#'
#' @return An object of class \code{"params"} containing simulation settings.
build_params <- function(
  off_R,
  off_k,
  gt_mu,
  gt_sd,
  epidemic_size,
  duration,
  replicates
) {
  offspring_dist <- list(
    name = "nbinom",
    parameters = list(k = off_k, R = off_R),
    r = function(n = 1) rnbinom(n = n, size = off_k, mu = off_R),
    d = function(x) dnbinom(x, size = off_k, mu = off_R)
  )

  gt_cv <- gt_sd / gt_mu
  gt_params <- epitrix::gamma_mucv2shapescale(mu = gt_mu, cv = gt_cv)
  generation_time <- distcrete::distcrete(
    name = "gamma",
    shape = gt_params$shape,
    scale = gt_params$scale,
    interval = 1
  )
  generation_time$parameters <- list(
    mu = gt_mu,
    sd = gt_sd,
    cv = gt_cv,
    shape = gt_params$shape,
    scale = gt_params$scale
  )

  params <- list(
    offspring_dist = offspring_dist,
    generation_time = generation_time,
    epidemic_size = epidemic_size,
    duration = duration,
    replicates = replicates
  )
  class(params) <- "params"

  return(params)
}


# -------------------------------------------------
# True transmission tree
# -------------------------------------------------
#' Simulate a True Transmission Tree
#'
#' Simulates a single outbreak using specified epidemic parameters until exactly epidemic_size is reached -> THROUGH TRUNCATION.!!!
#'
#' @param params List of epidemic parameters generated by \code{build_params()}.
#'
#' @return A tibble with columns \code{from}, \code{to}, and \code{date}, representing transmission events.
#'
build_tree <- function(params) {
  repeat_tree <- function(rep_id) {
    repeat {
      out <- simulacr::simulate_outbreak(
        duration = params$duration,
        population_size = 1e4,
        R_values = params$offspring_dist$r(params$epidemic_size),
        dist_generation_time = params$generation_time$d(0:params$duration),
        dist_incubation = 1L
      )$data

      # Check if the outbreak has reached at least epidemic_size
      size_OK <- nrow(out) >= params$epidemic_size
      if (size_OK) break
    }

    tree <- out |>
      slice(1:params$epidemic_size) |> # Truncate to exactly epidemic_size
      transmute(
        from = source,
        to = id,
        date = date_infection # row_number() @CyGei Do we have to avoid same dates?
      ) |>
      relabel_tree(id_cols = c("from", "to"), date_col = "date") |>
      as_tibble()

    mixtree::validate_tree(tree |> slice(-1))

    return(tree)
  }

  lapply(X = seq_len(params$replicates), FUN = repeat_tree)
}

# -------------------------------------------------
# Epidemic forest
# -------------------------------------------------
#' Simulate an Epidemic Forest
#'
#' Generates multiple plausible transmission trees given \code{tree} and \code{params}.
#'
#' @param tree A tibble representing the reference tree (from \code{build_tree()}).
#' @param params List of epidemic parameters generated by \code{build_params()}.
#' @param forest_size Integer. The total number of transmission trees to generate. Default is 200.
#'
#' @return A matrix of ancestries. Where each row corresponds to a tree and each column to a case (excluding the root).
#' For example, entry [i, j] indicates the infector of case j in tree i.
#'
# Internal function
.build_forest <- function(tree, params, forest_size = 200L) {
  simulate_tree <- function() {
    n_cases <- length(tree$to)

    # Sample offspring for all cases
    R <- params$offspring_dist$r(n_cases)

    # Ensure first case has R >= 1
    if (R[1] < 1) {
      R[1] <- LaplacesDemon::rtrunc(
        n = 1,
        spec = params$offspring_dist$name,
        a = 0,
        size = params$offspring_dist$parameters$k,
        mu = params$offspring_dist$parameters$R
      )
    }
    # Initialise tree
    sim_tree <- tibble(
      j = NA_character_, # infector
      i = tree$to, # infectee
      date = tree$date, # infectee's date is fixed from reference tree
      R = R # sampled offspring
    )

    generation_time_pmf <- params$generation_time$d(0:params$duration)

    for (row in 2:nrow(sim_tree)) {
      t_i <- sim_tree$date[row]

      j_candidates <- sim_tree |>
        filter(date < t_i) |>
        mutate(foi = R * generation_time_pmf[t_i - date + 1])

      j_chosen <- sample(
        j_candidates$i,
        1,
        prob = j_candidates$foi / sum(j_candidates$foi)
      )
      sim_tree$j[row] <- j_chosen
    }

    stopifnot(sum(is.na(sim_tree$j)) == 1) # one intro only

    sim_tree <- sim_tree |>
      slice(-1) |>
      rename(from = j, to = i)

    mixtree::validate_tree(sim_tree)

    # Return vector of ancestries to save space (i is always 1:n)
    ancestries <- as.vector(sim_tree$from)
    return(ancestries)
  }
  # Rows = forest ID, Columns = case ID
  forest <- t(replicate(forest_size, simulate_tree(), simplify = TRUE))
  colnames(forest) <- tree$to[-1] # Exclude root case
  return(forest)
}

# Exported function
build_forest <- function(param_id, tree_id, params, tree) {
  forest_tbl <- tibble(
    param_id = param_id,
    tree_id = tree_id,
    forest = list(.build_forest(tree, params))
  )
  return(forest_tbl)
}

# =================================================
# mixtree test wrapper
# =================================================
# Convert matrix to list of trees
as_forest <- function(forest) {
  n_rows <- nrow(forest)
  col_names <- colnames(forest)

  lapply(seq_len(n_rows), function(i) {
    data.frame(
      from = forest[i, ],
      to = col_names,
      stringsAsFactors = FALSE
    )
  })
}

# Run one test given sampled matrices
.mixtree_test <- function(sample_A, sample_B, method) {
  forest_A <- as_forest(sample_A)
  forest_B <- as_forest(sample_B)

  p_value <- switch(
    method,
    "permanova" = {
      test <- mixtree::tree_test(
        forest_A,
        forest_B,
        method = method,
        test_args = list(permutations = 100)
      )
      test[["Pr(>F)"]][[1]]
    },
    "chisq" = {
      test <- mixtree::tree_test(
        forest_A,
        forest_B,
        method = method,
        test_args = list(simulate.p.value = TRUE, B = 100)
      )
      test[["p.value"]]
    },
    stop("Unknown method: ", method)
  )
  return(p_value)
}

# Run all tests for one pair of forests
mixtree_test <- function(
  forests, # a list such that forests[[param_id]][[tree_id]] is a matrix of ancestries
  param_id_A,
  tree_id_A,
  param_id_B,
  tree_id_B,
  forest_sizes, #vector of sizes to test
  methods #vector of methods to test
) {
  forest_A <- forests[[param_id_A]][[tree_id_A]]
  forest_B <- forests[[param_id_B]][[tree_id_B]]

  grid <- expand_grid(
    forest_size = forest_sizes,
    method = methods
  )

  results <- purrr::pmap_dfr(grid, function(forest_size, method) {
    # Sample once per size
    sample_A <- forest_A[sample(nrow(forest_A), forest_size), , drop = FALSE]
    sample_B <- forest_B[sample(nrow(forest_B), forest_size), , drop = FALSE]
    p_value <- suppressWarnings(.mixtree_test(sample_A, sample_B, method))

    data.frame(
      param_id_A = param_id_A,
      tree_id_A = tree_id_A,
      param_id_B = param_id_B,
      tree_id_B = tree_id_B,
      forest_size = forest_size,
      method = method,
      p_value = p_value
    )
  })

  return(results)
}
