#' Relabel IDs by Onset Date
#'
#' Assigns new integer labels to a vector of IDs, ordered by their associated onset dates.
#' Returns a named vector mapping the original IDs to their new labels.
#'
#' @param id Character or factor vector of unique IDs.
#' @param date Vector of onset dates corresponding to \code{id}. Must be the same length as \code{id}.
#'
#' @return Character vector of new labels, named by original IDs and ordered as \code{id}.

label_ids <- function(id, date) {
  ordered_ids <- id[order(date)]
  new_labels <- as.character(seq_along(ordered_ids))
  setNames(new_labels, ordered_ids)[id]
}

#' Relabel Data Frame ID Columns
#' Replaces values in specified ID columns of a data frame with new labels ordered by onset date.
#' All ID columns are relabelled consistently using the same mapping.
#'
#' @param df Data frame. The transmission tree
#' @param id_cols Character vector of column names in \code{df} to relabel (e.g., \code{c("from", "to")}).
#' @param date_col Character. Name of the column containing onset or infection dates. Default in "date"
#'
#' @return Data frame with updated ID columns.
relabel_tree <- function(df, id_cols, date_col = "date") {
  ids <- label_ids(df[[id_cols[2]]], df[[date_col]]) # Use the 2nd column for labelling

  # Apply the relabelling all specified id columns
  for (col in id_cols) {
    df[[col]] <- ids[df[[col]]]
  }

  return(df)
}


# =================================================
# Tree generation
# =================================================

# -------------------------------------------------
# Epidemic Parameters
# -------------------------------------------------
print.params <- function(x, ...) {
  cat("-------------------\n")
  cat("Epidemic Parameters\n")
  cat("-------------------\n")

  # Offspring distribution
  cat("Distributions:\n")
  cat(" Offspring:\n")
  cat("  name:", x$offspring_dist$name, "\n")
  cat("  parameters:\n")
  cat("   k (size):", x$offspring_dist$parameters$k, "\n")
  cat("   R (mu):", x$offspring_dist$parameters$R, "\n\n")

  # Generation time distribution
  cat(" Generation time:\n")
  cat("  name:", x$generation_time$name, "\n")
  cat("  parameters:\n")
  cat("   shape:", x$generation_time$parameters$shape, "\n")
  cat("   scale:", x$generation_time$parameters$scale, "\n")
  cat("   mu:", x$generation_time$parameters$mu, "\n")
  cat("   sd:", x$generation_time$parameters$sd, "\n")
  cat("   cv:", x$generation_time$parameters$cv, "\n\n")

  # Other parameters
  cat("Simulation settings:\n")
  cat(" number of cases:", x$n_cases, "\n")
  cat(" simulation duration:", x$duration, "\n")
  cat(" n_trees:", x$n_trees, "\n")

  invisible(x)
}

#' Build Epidemic Model Parameters
#'
#' Constructs a list of parameters for simulating an epidemic forest, including the offspring distribution,
#' generation time distribution, number of cases, simulation duration, and number of trees.
#'
#' @param off_R Numeric. Mean of the offspring distribution.
#' @param off_k Numeric. Dispersion parameter of the negative binomial offspring distribution.
#' @param gt_mu Numeric. Mean generation time.
#' @param gt_sd Numeric. Standard deviation of generation time.
#' @param n_cases Integer. Target number of cases in the outbreak.
#' @param duration Integer. Duration of the simulation (in days).
#' @param n_trees Integer. Number of transmission trees to generate.
#'
#' @return An object of class \code{"params"} containing simulation settings.
build_params <- function(off_R, off_k, gt_mu, gt_sd, n_cases, duration, n_trees) {
  offspring_dist <- list(
    name = "nbinom",
    parameters = list(k = off_k, R = off_R),
    r = function(n = 1) rnbinom(n = n, size = off_k, mu = off_R),
    d = function(x) dnbinom(x, size = off_k, mu = off_R)
  )


  gt_cv <- gt_sd / gt_mu
  gt_params <- epitrix::gamma_mucv2shapescale(mu = gt_mu, cv = gt_cv)
  generation_time <- distcrete::distcrete(
    name = "gamma",
    shape = gt_params$shape,
    scale = gt_params$scale,
    interval = 1
  )
  generation_time$parameters <- list(
    mu = gt_mu,
    sd = gt_sd,
    cv = gt_cv,
    shape = gt_params$shape,
    scale = gt_params$scale
  )

  params <- list(
    offspring_dist = offspring_dist,
    generation_time = generation_time,
    n_cases = n_cases,
    duration = duration,
    n_trees = n_trees
  )
  class(params) <- "params"

  return(params)
}


# -------------------------------------------------
# True transmission tree
# -------------------------------------------------
#' Simulate a True Transmission Tree
#'
#' Simulates a single outbreak using specified epidemic parameters until exactly n_cases are generated.
#'
#' @param params List of epidemic parameters generated by \code{build_params()}.
#'
#' @return A tibble with columns \code{from}, \code{to}, and \code{date}, representing transmission events.
#'
build_tree <- function(params) {
  expected_AR <- epitrix::R02AR(params$offspring_dist$parameters$R)

  repeat {
    out <- simulacr::simulate_outbreak(
      duration = params$duration,
      population_size = round(params$n_cases / expected_AR),
      R_values = params$offspring_dist$r(params$n_cases),
      dist_generation_time = params$generation_time$d(0:params$duration),
      dist_incubation = 1L
    )

    # Check if we have exactly the target number of cases
    if (nrow(out$data) == params$n_cases) break
  }

  true_tree <- out$data |>
    transmute(
      from = source,
      to = id,
      date = date_infection #row_number() @CyGei Do we have to avoid same dates?
    ) |>
    relabel_tree(id_cols = c("from", "to"), date_col = "date") |>
    as_tibble()

  mixtree::validate_tree(true_tree |> slice(-1))

  return(true_tree)
}

# -------------------------------------------------
# Epidemic forest
# -------------------------------------------------
#' Simulate an Epidemic Forest
#'
#' Generates multiple plausible transmission trees given \code{true_tree} and \code{params}.
#'
#' @param true_tree A tibble representing the true outbreak tree (from \code{build_tree()}).
#' @param params List of epidemic parameters generated by \code{build_params()}.
#'
#' @return A list of transmission trees (tibbles), each with columns \code{from}, \code{to}, and \code{date}.
build_forest <- function(true_tree, params) {
  simulate_tree <- function() {
    sim_tree <- true_tree |>
      rename(j = from, i = to) |>
      mutate(
        j = NA_character_,
        R = params$offspring_dist$r(n()),

        # Ensure that the first case (i == "1") has R >= 1
        R = if_else(
          i == "1" & R < 1,
          LaplacesDemon::rtrunc(
            n = 1,
            spec = params$offspring_dist$name,
            a = 0,
            size = params$offspring_dist$parameters$k,
            mu = params$offspring_dist$parameters$R
          ), # Sample from non-zero R values
          R
        )
      )
    
    generation_time_pmf <- params$generation_time$d(0:params$duration)

    for (row in 2:nrow(sim_tree)) {
      i <- sim_tree$i[row]
      t_i <- sim_tree$date[row]

      j_candidates <- sim_tree |>
        filter(date < t_i) |>
        mutate(foi = R * generation_time_pmf[t_i - date + 1])
      # |>
      #   filter(foi > 0)

      # if (nrow(j_candidates) == 0) next

      j_chosen <- sample(j_candidates$i, 1, prob = j_candidates$foi / sum(j_candidates$foi))
      sim_tree$j[row] <- j_chosen
    }
    # safety checks
    stopifnot(sum(is.na(sim_tree$j)) == 1) # one intro only

    sim_tree <- sim_tree |>
      slice(-1) |>
      rename(from = j, to = i) # ignore intro row

    mixtree::validate_tree(sim_tree)
    return(sim_tree)
  }

  sim_trees <- replicate(params$n_trees, simulate_tree(), simplify = FALSE)
  return(sim_trees)
}


# -------------------------------------------------
# Forest checks
# -------------------------------------------------

# Function to check consistency and variation in columns across all data frames in the list
check_forest <- function(forest) {
  # Extract 'to' and 'date' columns from the first data frame as a reference
  ref_to <- forest[[1]]$to
  ref_date <- forest[[1]]$date
  ref_R <- forest[[1]]$R
  ref_from <- forest[[1]]$from

  # Check if 'to' and 'date' are consistent in all data frames
  consistent_to_date <- all(
    sapply(forest, function(df) {
      all(df$to == ref_to) && all(df$date == ref_date)
    })
  )

  # Check if 'R' and 'from' columns vary across data frames
  vary_R_from <- any(
    sapply(forest, function(df) {
      !all(df$R == ref_R) || !all(df$from == ref_from)
    })
  )

  # Return a list with both checks
  checks <- list(
    consistent_to_date = consistent_to_date,
    vary_R_from = vary_R_from
  )

  return(checks)
}

# Perform the test  -------------------------------------------------

#' Compute P-values from Resampled forests
#'
#' Draws resampled forests from two input forests (`forestA` and `forestB`) based on specified
#' probabilities, then compares each resampled pair using `mixtree::tree_test()` to
#' compute p-values.
#'
#' @param forestA A vector or list representing the first forest.
#' @param forestB A vector or list representing the second forest.
#' @param overlap_freq Numeric. The probability weight for sampling from `forestA` in the mixed forest.
#'   The weight for `forestB` is computed as (1 - overlap_freq).
#' @param sample_size Integer. The number of samples to draw per replicate.
#' @param n_repeats Integer. The number of replicates to perform.
#' @param method Character. The method to use for comparing forests. Default is "permanova" (see `mixtree::tree_test()`).
#' @param args List. Additional arguments to pass to `mixtree` functions.
#'
#' @return A numeric vector of p-values, one for each replicate.

get_pval <- function(forestA,
                     forestB,
                     overlap_freq,
                     sample_size,
                     n_repeats,
                     method = "permanova",
                     test_args = list()) {
  # Probabilities
  lenA <- length(forestA)
  lenB <- length(forestB)
  total_forest <- c(forestA, forestB)
  total_len <- lenA + lenB

  pA <- overlap_freq
  pB <- 1 - pA
  probs <- c(rep(pA / lenA, lenA), rep(pB / lenB, lenB))


  # Draw sample indices for all replicates in one go
  mix_idx <- matrix(
    sample.int(
      total_len,
      size = sample_size * n_repeats,
      prob = probs,
      replace = TRUE
    ),
    nrow = n_repeats
  )

  ref_idx <- matrix(sample.int(lenA, size = sample_size * n_repeats, replace = TRUE),
    nrow = n_repeats
  )

  p_values <- vapply(seq_len(n_repeats), function(i) {
    mixed_forest <- total_forest[mix_idx[i, ]]
    reference_forest <- forestA[ref_idx[i, ]]
    suppressWarnings(mixtree::tree_test(reference_forest, mixed_forest, method = method, test_args = args)[, "Pr(>F)"][1])
  }, numeric(1))

  return(p_values)
}




# Plot --------------------------------------------------------------------

#' Plot Proportions of Rejected Null Hypotheses
#' @param results A data frame containing the results of the peformance study.
#' @param alpha Numeric. The significance level. Default is 0.05.
#' @return A ggplot object.


plot_props <- function(results, alpha = 0.05) {
  annotations_df <- results %>%
    group_by(epidemic_size, sample_size, overlap_freq) %>%
    summarise(
      reject = mean(p_value < alpha) * 100,
      accept = mean(p_value >= alpha) * 100,
      .groups = "drop"
    ) %>%
    pivot_longer(
      cols = c("reject", "accept"),
      names_to = "category",
      values_to = "percentage"
    ) %>%
    mutate(
      row_title = "Epidemic Size",
      col_title = "Posterior Sample Size",
      # Create a label column with clear logic
      label = case_when(
        round(percentage, 1) == 100 ~ as.character(round(percentage, 1)),
        round(percentage, 1) == 0 ~ "",
        TRUE ~ as.character(round(percentage, 1))
      )
    )

  p <- annotations_df %>%
    ggplot(aes(x = overlap_freq, y = percentage, fill = category)) +
    geom_bar(
      stat = "identity",
      position = "stack",
      width = 0.775,
      color = "white",
      linewidth = 0.1
    ) +
    geom_text(
      aes(
        y = ifelse(
          percentage == 100,
          50,
          # Center the label when percentage is 100%
          ifelse(category == "reject", percentage / 2, 98.25 - percentage / 2)
        ),
        label = label
      ),
      colour = "black",
      size = 2.5
    ) +
    ggh4x::facet_nested(
      rows = vars(row_title, epidemic_size),
      cols = vars(col_title, sample_size),
      scales = "fixed",
      space = "fixed",
      remove_labels = "none",
      nest_line = element_line(
        colour = "black",
        linewidth = 0.05,
        lineend = "square"
      )
    ) +
    scale_fill_manual(
      values = c("reject" = "#1b81bc", "accept" = "#E69F00"), # af245a
      # 7d8af0 #82750f #0F8233
      breaks = c("reject", "accept"),
      name = "",
      labels = c("reject" = "Reject H0", "accept" = "Accept H0")
    ) +
    coord_cartesian(ylim = c(0, 100)) +
    theme_bw() +
    theme(
      legend.position = "bottom",
      legend.margin = margin(t = -15),
      strip.background = element_rect(
        fill = "#f8f4f2",
        colour = "black",
        linewidth = 0.5
      ),
      strip.text = element_text(family = "Fira Code", size = 10),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      panel.grid = element_blank()
      # panel.spacing = unit(0.25, "lines")
    ) +
    guides(
      fill =
        guide_legend(
          keywidth = 5,
          keyheight = 1,
          label.position = "top",
          label.vjust = -9.5
        )
    ) +
    labs(x = "Overlap Frequency", y = "Percentage")

  return(p)
}




# ROC ---------------------------------------------------------------------
get_roc <- function(data,
                    group_vars = c("sample_size", "epidemic_size")) {
  data %>%
    mutate(
      overlap_freq = as.integer(as.character(overlap_freq)),
      truth = if_else(overlap_freq < 1, 1, 0)
    ) %>%
    group_by(across(all_of(group_vars))) %>%
    group_modify(~ {
      roc_obj <- pROC::roc(
        response = .x$truth,
        predictor = .x$p_value,
        direction = ">",
        quiet = TRUE
      )

      roc_coords <- pROC::coords(
        roc_obj,
        "all",
        ret = c("threshold", "sensitivity", "specificity"),
        transpose = FALSE
      )

      youdens_j <- roc_coords$sensitivity + roc_coords$specificity - 1
      best_index <- which.max(youdens_j)
      best_alpha_value <- roc_coords$threshold[best_index]

      tibble::tibble(
        alpha = roc_coords$threshold,
        sensitivity = roc_coords$sensitivity,
        specificity = roc_coords$specificity,
        AUC = as.numeric(pROC::auc(roc_obj)),
        best_alpha = roc_coords$threshold == best_alpha_value
      )
    }) %>%
    ungroup()
}



plot_roc <- function(df,
                     group_vars = NULL,
                     facet_rows = NULL,
                     facet_cols = NULL,
                     row_title = NULL,
                     col_title = NULL,
                     color_var = "sample_size",
                     color_palette = "Blues",
                     point_shapes = c("Alpha = 0.05" = 21, "Best Alpha" = 24),
                     alpha_values = c(0.05),
                     title = NULL,
                     subtitle = NULL,
                     x_label = "1 - Specificity",
                     y_label = "Sensitivity") {
  # Get ROC data if raw results are provided
  if ("AUC" %in% names(df)) {
    x <- df
  } else {
    if (is.null(group_vars)) {
      stop("If providing raw results, you must specify group_vars")
    }
    x <- get_roc(df, group_vars = group_vars)
  }

  # Set up facet variables
  if (!is.null(row_title) && !is.null(facet_rows)) {
    x <- x %>% mutate(row_title = row_title)
  }

  if (!is.null(col_title) && !is.null(facet_cols)) {
    x <- x %>% mutate(col_title = col_title)
  }

  # Create points dataframe for multiple alpha values
  points_df_list <- list()

  # Add points for specified alpha values
  for (a in alpha_values) {
    points_df_list[[paste0("Alpha = ", a)]] <- x %>%
      group_by_at(vars(one_of(c(color_var, facet_rows, facet_cols)))) %>%
      slice_min(abs(alpha - a)) %>%
      ungroup() %>%
      mutate(point_type = paste0("Alpha = ", a))
  }

  # Add points for best alpha
  points_df_list[["Best Alpha"]] <- x %>%
    filter(best_alpha) %>%
    mutate(point_type = "Best Alpha")

  points_df <- bind_rows(points_df_list)

  # Create annotations
  group_vars_for_annotation <- c()
  if (!is.null(col_title) && !is.null(facet_cols)) {
    group_vars_for_annotation <- c(group_vars_for_annotation, "col_title", facet_cols)
  } else if (!is.null(facet_cols)) {
    group_vars_for_annotation <- c(group_vars_for_annotation, facet_cols)
  }

  if (!is.null(row_title) && !is.null(facet_rows)) {
    group_vars_for_annotation <- c(group_vars_for_annotation, "row_title", facet_rows)
  } else if (!is.null(facet_rows)) {
    group_vars_for_annotation <- c(group_vars_for_annotation, facet_rows)
  }

  if (length(group_vars_for_annotation) == 0) {
    group_vars_for_annotation <- color_var
  }

  annotations <- x %>%
    filter(best_alpha) %>%
    group_by_at(vars(one_of(c(color_var, group_vars_for_annotation)))) %>%
    summarise(
      AUC = unique(AUC),
      AUC = round(AUC, digits = 3),
      best_alpha_value = unique(alpha),
      best_alpha_value = round(best_alpha_value, digits = 3),
      .groups = "drop"
    ) %>%
    mutate(
      label = paste0('"AUC = " * ', AUC, ' * "," ~ ', 'alpha^"*" == ', best_alpha_value),
      x = 0.3,
      y = 0.05 + (as.integer(get(color_var)) - 1) * 0.075
    )

  # Prepare faceting formula
  facet_formula <- NULL
  if (!is.null(facet_rows) && !is.null(facet_cols)) {
    if (!is.null(row_title) && !is.null(col_title)) {
      facet_formula <- ggh4x::facet_nested(
        rows = vars(row_title, !!!syms(facet_rows)),
        cols = vars(col_title, !!!syms(facet_cols)),
        scales = "fixed",
        space = "fixed"
      )
    } else {
      facet_formula <- ggh4x::facet_nested(
        rows = vars(!!!syms(facet_rows)),
        cols = vars(!!!syms(facet_cols)),
        scales = "fixed",
        space = "fixed"
      )
    }
  } else if (!is.null(facet_rows)) {
    if (!is.null(row_title)) {
      facet_formula <- ggh4x::facet_nested(
        rows = vars(row_title, !!!syms(facet_rows)),
        scales = "fixed",
        space = "fixed"
      )
    } else {
      facet_formula <- ggh4x::facet_nested(
        rows = vars(!!!syms(facet_rows)),
        scales = "fixed",
        space = "fixed"
      )
    }
  } else if (!is.null(facet_cols)) {
    if (!is.null(col_title)) {
      facet_formula <- ggh4x::facet_nested(
        cols = vars(col_title, !!!syms(facet_cols)),
        scales = "fixed",
        space = "fixed"
      )
    } else {
      facet_formula <- ggh4x::facet_nested(
        cols = vars(!!!syms(facet_cols)),
        scales = "fixed",
        space = "fixed"
      )
    }
  }

  # Build plot
  p <- ggplot()

  if (!is.null(facet_formula)) {
    p <- p + facet_formula
  }

  p <- p +
    geom_line(data = x, aes_string(
      x = "1 - specificity",
      y = "sensitivity",
      color = color_var
    )) +
    geom_point(
      data = points_df,
      aes_string(
        x = "1 - specificity",
        y = "sensitivity",
        fill = color_var,
        shape = "point_type"
      ),
      color = "black",
      stroke = 0.5
    ) +
    geom_text(
      data = annotations,
      aes_string(
        x = "x",
        y = "y",
        color = color_var,
        label = "label"
      ),
      parse = TRUE,
      hjust = 0,
      vjust = 1,
      size = 3,
      show.legend = FALSE
    ) +
    geom_abline(
      slope = 1,
      intercept = 0,
      linetype = "dashed",
      color = "grey"
    ) +
    coord_fixed(ratio = 1) +
    theme_bw() +
    theme(
      legend.position = "bottom",
      legend.box = "vertical",
      legend.margin = margin(t = -5),
      strip.background = element_rect(
        fill = "#f8f4f2",
        colour = "black",
        linewidth = 0.5
      ),
      strip.text = element_text(family = "Fira Code", size = 10),
      panel.grid = element_blank()
    ) +
    guides(
      color = guide_legend(
        title = gsub("_", " ", tools::toTitleCase(color_var)),
        order = 1,
        override.aes = list(shape = NA)
      ),
      shape = guide_legend(title = "Point Type", order = 2),
      fill = "none"
    ) +
    colorspace::scale_color_discrete_sequential(palette = color_palette, nmax = 8, order = 5:8) +
    colorspace::scale_fill_discrete_sequential(palette = color_palette, nmax = 8, order = 5:8) +
    scale_shape_manual(values = point_shapes) +
    labs(
      x = x_label,
      y = y_label,
      title = title,
      subtitle = subtitle
    )

  return(p)
}

save_safely <- function(object, file) {
  if (file.exists(file)) {
    stop(paste("File", file, "already exists. Choose a different filename."))
  } else {
    saveRDS(object, file)
  }
}
# plot_roc(rocs,
#          facet_rows = "method",
#          facet_cols = "epidemic_size",
#          row_title = "Method",
#          col_title = "Epidemic Size",
#          color_var = "sample_size",
#          color_palette = "Purples")
#
# plot_roc(chi_results,
#          group_vars = c("sample_size", "epidemic_size"),
#          facet_cols = "epidemic_size",
#          col_title = "Epidemic Size",
#          color_var = "sample_size")


# plot_roc <- function(df) {
#   x <- get_roc(df) %>%
#     mutate(col_title = "Epidemic Size")
#
#   points_df <- bind_rows(
#     x %>%
#       group_by(sample_size, epidemic_size) %>%
#       slice_min(abs(alpha - 0.05)) %>%
#       ungroup() %>%
#       mutate(point_type = "Alpha = 0.05"),
#     x %>%
#       filter(best_alpha) %>%
#       mutate(point_type = "Best Alpha")
#   )
#
#   annotations <- x %>%
#     filter(best_alpha) %>%
#     group_by(col_title, sample_size, epidemic_size) %>%
#     summarise(
#       AUC = unique(AUC),
#       AUC = round(AUC, digits = 3),
#       best_alpha_value = unique(alpha),
#       best_alpha_value = round(best_alpha_value, digits = 3),
#       .groups = "drop"
#     ) %>%
#     mutate(
#       label = paste0('"AUC = " * ', AUC, ' * "," ~ ', 'alpha^"*" == ', best_alpha_value),
#       x = 0.3,
#       y = 0.05 + (as.integer(sample_size) - 1) * 0.075
#     )
#
#
#   p <- ggplot() +
#     ggh4x::facet_nested(
#       cols = vars(col_title, epidemic_size),
#       scales = "fixed",
#       space = "fixed"
#     ) +
#     geom_line(data = x,
#               aes(
#                 x = 1 - specificity,
#                 y = sensitivity,
#                 color = sample_size
#               )) +
#     geom_point(
#       data = points_df,
#       aes(
#         x = 1 - specificity,
#         y = sensitivity,
#         fill = sample_size,
#         shape = point_type
#       ),
#       color = "black",
#       stroke = 0.5
#     ) +
#     geom_text(
#       data = annotations,
#       aes(
#         x = x,
#         y = y,
#         color = sample_size,
#         label = label
#       ),
#       parse = TRUE,
#       hjust = 0,
#       vjust = 1,
#       size = 3,
#       show.legend = FALSE
#     ) +
#     geom_abline(
#       slope = 1,
#       intercept = 0,
#       linetype = "dashed",
#       color  = "grey"
#     ) +
#     coord_fixed(ratio = 1) +
#     theme_bw() +
#     theme(
#       legend.position = "bottom",
#       legend.box = "vertical",
#       legend.margin = margin(t = -5),
#       strip.background = element_rect(
#         fill = "#f8f4f2",
#         colour = "black",
#         linewidth = 0.5
#       ),
#       strip.text = element_text(family = "Fira Code", size = 10),
#       panel.grid = element_blank()
#     ) +
#     guides(
#       color = guide_legend(
#         title = "Sample Size",
#         order = 1,
#         override.aes = list(shape = NA)
#       ),
#       shape = guide_legend(title = "Point Type", order = 2),
#       fill = "none"
#     ) +
#     colorspace::scale_color_discrete_sequential(palette = "Blues",
#                                                 nmax = 8,
#                                                 order = 5:8) +
#     colorspace::scale_fill_discrete_sequential(palette = "Blues",
#                                                nmax = 8,
#                                                order = 5:8) +
#     scale_shape_manual(values = c("Alpha = 0.05" = 21, "Best Alpha" = 24)) +
#     labs(x = "1 - Specificity", y = "Sensitivity")
#
#   return(p)
# }
